Update to kargo-render rc34
kargo-rencer rc.34 introduced significant changes to the `kargo-render.yaml` file structure.

The underlying error I am trying to work around is:

```
 Error: error loading Kargo Render configuration from repo: error normalizing and validating Kargo Render configuration: error validating Kargo Render configuration: branchConfigs.0.appConfigs.testservice.configManagement: Must validate one and only one schema (oneOf); branchConfigs.0.appConfigs.testservice.configManagement: Additional property path is not allowed; branchConfigs.0.appConfigs.testservice.configManagement.helm: Additional property valueFiles is not allowed
```

I believe this is because my `kargo-render.yaml` file is set up to work with rc.34, but kargo is still importing rc.33.

Signed-off-by: Samuel Suter <samuel@suter.is>